# Generated by Django 6.0.6 on 2026-08-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enabled_modules',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landing_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landing_tagline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landing_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='product_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('restaurant', 'Restaurant'), ('mixed', 'Hotel + Restaurant')], db_index=True, default='hotel', max_length=20),
        ),
    ]
