# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_contacts', to='api.tenant')),
            ],
            options={
                'db_table': 'website_contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
