# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_website_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('guest_name', models.CharField(blank=True, default='', max_length=200)),
                ('room_number', models.CharField(blank=True, default='', max_length=50)),
                ('item', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='open', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='api.tenant')),
            ],
            options={'db_table': 'service_bookings', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ChannelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('property_code', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='api.tenant')),
            ],
            options={'db_table': 'channel_mappings', 'ordering': ['channel_name']},
        ),
    ]
