# Generated by Django 6.0.6 on 2026-08-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_gyoroom_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='active', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_records', to='api.tenant')),
            ],
            options={
                'db_table': 'catalog_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'kind'], name='catalog_rec_tenant__780eb2_idx')],
            },
        ),
    ]
