# Generated by Django 6.0.6 on 2026-08-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_catalog_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=80)),
                ('reference', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(db_index=True, default='open', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_records', to='api.tenant')),
            ],
            options={
                'db_table': 'ops_records',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'kind', 'status'], name='ops_records_tenant__dd9d98_idx')],
            },
        ),
    ]
