# Generated by Django 6.0.6 on 2026-08-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_ops_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='extra_bed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RoomTypeSpecialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('rate_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_rates', to='api.rateplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_rates', to='api.roomtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type_special_rates', to='api.tenant')),
            ],
            options={
                'db_table': 'room_type_special_rates',
            },
        ),
    ]
