# Generated by Django 6.0.6 on 2026-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_frontdesk_special_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='book',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='voucher_type',
            field=models.CharField(db_index=True, default='journal', max_length=30),
        ),
    ]
