# Generated by Django 6.0.7 on 2026-08-13 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_hr_crm_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='channel',
            field=models.CharField(default='in_app', max_length=20),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='recipient_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AcceptedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_payment_methods', to='api.tenant')),
            ],
            options={
                'db_table': 'accepted_payment_methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('modules', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_roles', to='api.tenant')),
            ],
            options={
                'db_table': 'app_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_types', to='api.tenant')),
            ],
            options={
                'db_table': 'asset_types',
            },
        ),
        migrations.CreateModel(
            name='AssetVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_vendors', to='api.tenant')),
            ],
            options={
                'db_table': 'asset_vendors',
            },
        ),
        migrations.CreateModel(
            name='AssetVendorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_vendor_contracts', to='api.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.assetvendor')),
            ],
            options={
                'db_table': 'asset_vendor_contracts',
            },
        ),
        migrations.CreateModel(
            name='NearbyTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='airport', max_length=40)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_terminals', to='api.tenant')),
            ],
            options={
                'db_table': 'nearby_terminals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='api.tenant')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_blogs', to='api.tenant')),
            ],
            options={
                'db_table': 'utility_blogs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UtilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.CharField(default='14:00', max_length=8)),
                ('check_out_time', models.CharField(default='12:00', max_length=8)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('service_charge_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sms_unit_cost', models.DecimalField(decimal_places=4, default=0.5, max_digits=10)),
                ('night_audit_time', models.CharField(default='23:59', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utility_settings', to='api.tenant')),
            ],
            options={
                'db_table': 'utility_settings',
            },
        ),
        migrations.CreateModel(
            name='UserAccountPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_post_vouchers', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('can_manage_coa', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_permissions', to='api.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account_permissions',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
