# Generated by Django 6.0.7 on 2026-08-14 04:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_convert_usd_amounts_to_bdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCounterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('role_type', models.CharField(default='other', max_length=32)),
                ('party_kind', models.CharField(default='other', max_length=20)),
                ('opening_balance_type', models.CharField(default='zero', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_balance_as_of', models.DateField(blank=True, null=True)),
                ('opening_interest_applicable', models.BooleanField(default=False)),
                ('opening_annual_interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_id', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_balance_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_counterparty_openings', to='api.journalentry')),
                ('opening_equity_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_counterparties_opening_equity', to='api.chartofaccount')),
                ('opening_principal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_counterparties_opening_principal', to='api.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_counterparties', to='api.tenant')),
            ],
            options={
                'db_table': 'loan_counterparty',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=16)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('banking_model', models.CharField(default='conventional', max_length=24)),
                ('product_type', models.CharField(default='general', max_length=32)),
                ('deal_reference', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('agreement_no', models.CharField(blank=True, default='', max_length=120)),
                ('islamic_contract_variant', models.CharField(blank=True, default='', max_length=24)),
                ('sanction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_repaid_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_interest', to='api.chartofaccount')),
                ('interest_accrual_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_interest_accrual', to='api.chartofaccount')),
                ('parent_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_loans', to='api.loan')),
                ('principal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_principal', to='api.chartofaccount')),
                ('settlement_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_settlement', to='api.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_loans', to='api.tenant')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='api.loancounterparty')),
            ],
            options={
                'db_table': 'loan',
                'ordering': ['-id'],
                'unique_together': {('tenant', 'loan_no')},
            },
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_disbursements', to='api.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='api.loan')),
            ],
            options={
                'db_table': 'loan_disbursement',
                'ordering': ['-disbursement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanInterestAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('days_basis', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_interest_accruals', to='api.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accruals', to='api.loan')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_accrual_reversals', to='api.journalentry')),
            ],
            options={
                'db_table': 'loan_interest_accrual',
                'ordering': ['-accrual_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('memo', models.TextField(blank=True, default='')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='api.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='api.loan')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment_reversals', to='api.journalentry')),
            ],
            options={
                'db_table': 'loan_repayment',
                'ordering': ['-repayment_date', '-id'],
            },
        ),
    ]
