# Generated by Django 6.0.7 on 2026-08-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_corporate_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_bearing',
            field=models.BooleanField(default=True),
        ),
    ]
