# Generated by Django 6.0.6 on 2026-08-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_coa_plain_codes_per_tenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chart_of_ac_tenant__da7eea_idx',
            old_name='chart_of_ac_tenant__7a2b1c_idx',
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_balance_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_balance_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coa_opening_accounts', to='api.journalentry'),
        ),
    ]
