# Generated by Django 6.0.6 on 2026-08-14 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_coa_opening_balance_as_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('guest', 'Guest'), ('customer', 'Customer'), ('company', 'Company'), ('vendor', 'Vendor'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('loan_counterparty', 'Loan counterparty'), ('other', 'Other')], db_index=True, max_length=32)),
                ('party_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_balance_as_of', models.DateField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_accounts', to='api.chartofaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_accounts', to='api.tenant')),
            ],
            options={
                'db_table': 'party_accounts',
            },
        ),
        migrations.CreateModel(
            name='PartyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('narration', models.TextField(blank=True, default='')),
                ('related_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_ledger_entries', to='api.journalentry')),
                ('party_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.partyaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_ledger_entries', to='api.tenant')),
            ],
            options={
                'db_table': 'party_ledger_entries',
            },
        ),
        migrations.AddIndex(
            model_name='partyaccount',
            index=models.Index(fields=['tenant', 'party_type', 'party_id'], name='party_accou_tenant__6ecf97_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaccount',
            index=models.Index(fields=['tenant', 'control_account'], name='party_accou_tenant__f67bb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partyaccount',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='partyledgerentry',
            index=models.Index(fields=['tenant', 'party_account', 'entry_date'], name='party_ledge_tenant__3b26b4_idx'),
        ),
    ]
