# Generated by Django 6.0.6 on 2026-08-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_party_subsidiary_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='accrual_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='api.journalentry'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='api.journalentry'),
        ),
    ]
