# Generated by Django 6.0.6 on 2026-08-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_payroll_gl_journals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('operations_manager', 'Operations Manager'), ('manager', 'Manager'), ('frontdesk', 'Frontdesk'), ('housekeeping', 'Housekeeping'), ('restaurant', 'Restaurant'), ('fnb', 'F&B'), ('accountant', 'Accountant'), ('purchase_officer', 'Purchase Officer'), ('maintenance', 'Maintenance'), ('staff', 'Staff')], default='staff', max_length=32),
        ),
    ]
