"""API URL configuration matching FastAPI route prefixes."""
from django.urls import path

from api.views import (
    accounts,
    assets,
    auth,
    banquet,
    config,
    core,
    crm,
    extras,
    fnb,
    fnb_config,
    folio,
    frontdesk,
    frontdesk_config,
    frontdesk_reports,
    hr,
    housekeeping,
    inventory,
    loans,
    ops,
    parties,
    public,
    remaining,
    reports,
    reservations,
    superadmin,
    utilities,
    website,
)

urlpatterns = [
    # Root & core
    path('', core.root),
    path('api/core/health/', core.health_check),

    # Authentication
    path('api/auth/login', auth.login),
    path('api/auth/refresh', auth.refresh_token),
    path('api/auth/me', auth.me),
    path('api/auth/register', auth.register),
    path('api/auth/roles', auth.roles_catalog),
    path('api/auth/access', auth.my_access),

    # Superadmin SaaS control panel
    path('api/superadmin/catalog', superadmin.catalog),
    path('api/superadmin/dashboard', superadmin.dashboard),
    path('api/superadmin/tenants', superadmin.tenants),
    path('api/superadmin/tenants/<int:tenant_id>', superadmin.tenant_detail),
    path('api/superadmin/revenue', superadmin.revenue),

    # Public landing / booking / ordering / domain resolve
    path('api/public/resolve', public.resolve_host),
    path('api/public/sites', public.public_sites),
    path('api/public/landing/<str:subdomain>', public.public_landing),
    path('api/public/<str:subdomain>/menu', public.public_menu),
    path('api/public/<str:subdomain>/stays', public.public_stays),
    path('api/public/<str:subdomain>/booking', public.public_booking),
    path('api/public/<str:subdomain>/stay', public.public_stay_lookup),
    path('api/public/<str:subdomain>/order', public.public_order),
    path('api/public/<str:subdomain>/order/pay', public.public_order_pay),
    path('api/public/<str:subdomain>/leads', public.public_leads_debug),
    path('api/public/<str:subdomain>/contact', website.public_contact),

    path('api/website/content', website.website_content),
    path('api/website/contacts', website.website_contacts),
    path('api/website/bookings', website.website_bookings),

    path('api/services/<int:pk>/action', extras.service_action),
    path('api/services', extras.service_bookings),
    path('api/channels', extras.channels),
    path('api/ops/<int:pk>/action', ops.ops_action),
    path('api/ops', ops.ops_records),
    path('api/catalog', extras.catalog),
    path('api/config', config.config_records),
    path('api/reports/catalog', reports.reports_catalog),
    path('api/reports/run', reports.run_report),

    # Housekeeping
    path('api/housekeeping/wake-up-calls', housekeeping.wake_up_calls),
    path('api/housekeeping/lost-found', housekeeping.lost_found),
    path('api/housekeeping/tasks', housekeeping.tasks),
    path('api/housekeeping/rooms/status', housekeeping.room_status_list),
    path('api/housekeeping/rooms/floors', housekeeping.floors),
    path('api/housekeeping/rooms/types', housekeeping.room_types),
    path('api/housekeeping/rooms/<int:room_id>/status', housekeeping.update_room_status),
    path('api/housekeeping/guest-status', remaining.guest_status_report),
    path('api/housekeeping/amenity-distribution/report', remaining.amenity_report),
    path('api/housekeeping/amenity-distribution', remaining.amenity_distributions),
    path('api/housekeeping/maintenance-block', remaining.maintenance_block),

    path('api/frontdesk/agent-funds/<int:pk>/action', remaining.agent_fund_action),
    path('api/frontdesk/agent-funds', remaining.agent_funds),

    # Frontdesk
    path('api/frontdesk/room-rack', frontdesk.room_rack),
    path('api/frontdesk/room-rack/floors', frontdesk.floors),
    path('api/frontdesk/room-rack/types', frontdesk.room_types),
    path('api/frontdesk/config/<str:kind>/<int:pk>', frontdesk_config.config_detail),
    path('api/frontdesk/config/<str:kind>', frontdesk_config.config_list),
    path('api/frontdesk/rate-schedule', frontdesk_config.rate_schedule),
    path('api/frontdesk/forecast/room-type', frontdesk_config.forecast_room_type),
    path('api/frontdesk/forecast/availability', frontdesk_config.forecast_availability),
    path('api/frontdesk/reports/<str:kind>', frontdesk_reports.frontdesk_report),

    # Reservations (specific paths before list)
    path('api/reservations/create', reservations.create_reservation),
    path('api/guests', reservations.guests),
    path('api/reservations/guests/search', reservations.search_guests),
    path('api/reservations/rooms/available', reservations.available_rooms),
    path('api/reservations/<int:pk>/check-in', folio.check_in),
    path('api/reservations/<int:pk>/check-out', folio.check_out),
    path('api/reservations/<int:pk>/cancel', folio.cancel_reservation),
    path('api/reservations/<int:pk>/folio', folio.folio),
    path('api/reservations/<int:pk>', folio.reservation_detail),
    path('api/reservations', reservations.list_reservations),

    # F&B
    path('api/fnb/menu-items', fnb.menu_items),
    path('api/fnb/menu-items/<int:item_id>', fnb.menu_item_detail),
    path('api/fnb/menus', fnb.menus),
    path('api/fnb/orders/<int:pk>/action', fnb.order_action),
    path('api/fnb/orders', fnb.orders),
    path('api/fnb/recipes/cost-analysis', fnb.recipe_cost_analysis),
    path('api/fnb/recipes/<int:recipe_id>', fnb.recipe_detail),
    path('api/fnb/recipes', fnb.recipes),
    path('api/fnb/ingredients/<int:ingredient_id>/stock', fnb.ingredient_stock),
    path('api/fnb/ingredients/<int:ingredient_id>', fnb.ingredient_detail),
    path('api/fnb/ingredients', fnb.ingredients),
    path('api/fnb/stock-movements', fnb.stock_movements),
    path('api/fnb/sales', fnb.sales),
    path('api/fnb/config/<str:kind>/<int:pk>', fnb_config.config_detail),
    path('api/fnb/config/<str:kind>', fnb_config.config_list),
    path('api/fnb/pos/statement', fnb_config.pos_statement),
    path('api/fnb/reports/<str:kind>', fnb_config.fnb_report),

    # Accounts
    path('api/accounts/chart-of-accounts/<int:pk>', accounts.account_detail),
    path('api/accounts/chart-of-accounts/erp-defaults', accounts.erp_defaults),
    path('api/accounts/chart-of-accounts', accounts.chart_of_accounts),
    path('api/accounts/vouchers/<int:pk>', accounts.voucher_detail),
    path('api/accounts/vouchers', accounts.vouchers),
    path('api/accounts/reports/<str:kind>', accounts.account_report),
    path('api/accounts/payable/payments', accounts.payable_payments),
    path('api/accounts/receivable/payments', accounts.receivable_payments),
    path('api/accounts/payable', accounts.payable),
    path('api/accounts/receivable', accounts.receivable),
    path('api/accounts/budgets', accounts.budgets),
    path('api/accounts/parties/aging', parties.party_aging_report),
    path('api/accounts/parties/reconcile', parties.party_reconcile),
    path('api/accounts/parties/<int:pk>', parties.party_account_detail),
    path('api/accounts/parties', parties.party_accounts),
    path('api/accounts/loans/meta', loans.loan_meta),
    path('api/accounts/loans/counterparties/<int:pk>', loans.loan_counterparty_detail),
    path('api/accounts/loans/counterparties', loans.loan_counterparties),
    path('api/accounts/loans/<int:pk>/disburse', loans.loan_disburse),
    path('api/accounts/loans/<int:pk>/repay', loans.loan_repay),
    path('api/accounts/loans/<int:pk>/repayments/<int:repayment_id>/reverse', loans.loan_repayment_reverse),
    path('api/accounts/loans/<int:pk>/accrue', loans.loan_accrue),
    path('api/accounts/loans/<int:pk>/accruals/<int:accrual_id>/reverse', loans.loan_accrual_reverse),
    path('api/accounts/loans/<int:pk>/schedule', loans.loan_schedule),
    path('api/accounts/loans/<int:pk>', loans.loan_detail),
    path('api/accounts/loans', loans.loans_list),

    # Inventory
    path('api/inventory/config/<str:kind>/<int:pk>', inventory.config_detail),
    path('api/inventory/config/<str:kind>', inventory.config_list),
    path('api/inventory/requisitions/<int:pk>/action', inventory.requisition_detail),
    path('api/inventory/requisitions/<int:pk>', inventory.requisition_detail),
    path('api/inventory/requisitions', inventory.requisitions),
    path('api/inventory/purchases/<int:pk>/action', inventory.purchase_detail),
    path('api/inventory/purchases/<int:pk>', inventory.purchase_detail),
    path('api/inventory/purchases', inventory.purchases),
    path('api/inventory/transfers/<int:pk>', inventory.transfer_detail),
    path('api/inventory/transfers', inventory.transfers),
    path('api/inventory/adjustments/<int:pk>', inventory.adjustment_detail),
    path('api/inventory/adjustments', inventory.adjustments),
    path('api/inventory/consumptions/<int:pk>', inventory.consumption_detail),
    path('api/inventory/consumptions', inventory.consumptions),
    path('api/inventory/payments', inventory.supplier_payments),
    path('api/inventory/suppliers/statement', inventory.supplier_statement),
    path('api/inventory/stock', inventory.stock),
    path('api/inventory/reports/<str:kind>', inventory.inventory_report),

    # Banquet
    path('api/banquet/config/<str:kind>/<int:pk>', banquet.config_detail),
    path('api/banquet/config/<str:kind>', banquet.config_list),
    path('api/banquet/events/<int:pk>/action', banquet.event_action),
    path('api/banquet/events/<int:pk>', banquet.event_detail),
    path('api/banquet/events', banquet.events),
    path('api/banquet/forecast', banquet.venue_forecast),
    path('api/banquet/reports/<str:kind>', banquet.banquet_report),

    # HR
    path('api/hr/config/<str:kind>/<int:pk>', hr.config_detail),
    path('api/hr/config/<str:kind>', hr.config_list),
    path('api/hr/attendance', hr.attendance),
    path('api/hr/leaves/<int:pk>/action', hr.leave_action),
    path('api/hr/leaves', hr.leaves),
    path('api/hr/loans/<int:pk>/action', hr.loan_action),
    path('api/hr/loans', hr.loans),
    path('api/hr/payroll/bulk-pay', hr.payroll_bulk_pay),
    path('api/hr/payroll/<int:pk>/action', hr.payroll_action),
    path('api/hr/payroll', hr.payroll),
    path('api/hr/settings', hr.settings_view),
    path('api/hr/dashboard', hr.dashboard),
    path('api/hr/reports/<str:kind>', hr.hr_report),

    # CRM
    path('api/crm/config/<str:kind>/<int:pk>', crm.config_detail),
    path('api/crm/config/<str:kind>', crm.config_list),
    path('api/crm/leads/<int:pk>/action', crm.lead_action),
    path('api/crm/leads', crm.leads),
    path('api/crm/quotations/<int:pk>/action', crm.quotation_action),
    path('api/crm/quotations', crm.quotations),
    path('api/crm/invoices/<int:pk>/action', crm.invoice_action),
    path('api/crm/invoices', crm.invoices),
    path('api/crm/tasks/<int:pk>/action', crm.task_action),
    path('api/crm/tasks', crm.tasks),
    path('api/crm/feedback/<int:pk>/action', crm.feedback_action),
    path('api/crm/feedback', crm.feedback),
    path('api/crm/comments', crm.comments),
    path('api/crm/reports/<str:kind>', crm.crm_report),

    # Assets & Maintenance (specific paths before list)
    path('api/assets/config/<str:kind>/<int:pk>', remaining.asset_config_detail),
    path('api/assets/config/<str:kind>', remaining.asset_config_list),
    path('api/assets/depreciation', assets.depreciation),
    path('api/assets/maintenance-schedules', assets.maintenance_schedules),
    path('api/assets/maintenance-history', assets.maintenance_history),
    path('api/assets/maintenance-requests', assets.maintenance_requests),
    path('api/assets/work-orders', assets.work_orders),
    path('api/assets', assets.assets_list),

    # Utilities
    path('api/utilities/settings', utilities.settings_view),
    path('api/utilities/users', utilities.users_list),
    path('api/utilities/config/<str:kind>/<int:pk>', remaining.util_config_detail),
    path('api/utilities/config/<str:kind>', remaining.util_config_list),
    path('api/utilities/additional-configs', remaining.additional_configs),
    path('api/utilities/account-permissions', remaining.account_permissions),
    path('api/utilities/activity-log', remaining.activity_log),
    path('api/utilities/clear-cache', remaining.clear_cache),
    path('api/utilities/backup', remaining.backup),

    # Broadcast
    path('api/broadcast/messages', remaining.broadcast_messages),
    path('api/broadcast/sms-cost', remaining.sms_cost_report),
]
